name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for creating your first issue, and welcome! Here is the blogmate commuinty. Please be nice! Someone will help you shortly "
        pr-message: "Thanks for creating your first pull requedt and welcome! Here is the blogmate suggest! Be nice and share good code. Someone will review it "
